on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      codespell_err: ${{ steps.spelling.outputs.codespell_err }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
      - name: spelling
        shell: sh
        continue-on-error: true
        run: |
          $?
          bob=$(echo $?)
          echo "::set-output name=codespell_err::${bob}"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}} ${{needs.job1.outputs.codespell_err}}
